In [10]:
import pandas as pd
df = pd.read_csv('X_train.csv')
df

,temperature,heart_rate,blood_oxygen,temperature_mean,temperature_std,temperature_min,temperature_max,temperature_change,heart_rate_mean,heart_rate_std,heart_rate_min,heart_rate_max,heart_rate_change,blood_oxygen_mean,blood_oxygen_std,blood_oxygen_min,blood_oxygen_max,blood_oxygen_change
0,36.299999,65.000000,100.0,36.299999,0.000000,36.299999,36.299999,0.00000,65.000000,0.000000,65.000000,65.000000,0.000000,100.000000,0.000000,100.0,100.0,0.0
1,36.900002,126.000000,94.0,36.900002,0.000000,36.900002,36.900002,0.00000,106.666667,12.675436,91.000000,126.000000,35.000000,97.833333,3.371449,93.0,100.0,-6.0
2,36.000000,65.000000,100.0,36.000000,0.000000,36.000000,36.000000,0.00000,63.000000,2.097618,60.000000,65.000000,0.000000,100.000000,0.000000,100.0,100.0,0.0
3,36.400002,60.000000,97.0,36.400002,0.000000,36.400002,36.400002,0.00000,60.000000,0.000000,60.000000,60.000000,0.000000,97.000000,0.000000,97.0,97.0,0.0
4,36.000000,66.000000,97.0,36.000000,0.000000,36.000000,36.000000,0.00000,64.500000,1.048809,63.000000,66.000000,3.000000,97.000000,0.000000,97.0,97.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18474,38.566950,75.712484,100.0,39.064342,0.320050,38.566950,39.390000,-0.82305,77.288173,3.384308,73.658260,82.089381,2.054224,100.000000,0.000000,100.0,100.0,0.0
18475,36.406836,73.068349,100.0,36.404996,0.001377,36.403155,36.406836,0.00368,68.883281,2.939717,66.031546,73.068349,7.036803,100.000000,0.000000,100.0,100.0,0.0
18476,36.435436,62.354364,100.0,36.433595,0.001377,36.431755,36.435436,0.00368,62.335962,0.013771,62.317560,62.354364,0.036803,100.000000,0.000000,100.0,100.0,0.0
18477,36.200001,71.000000,100.0,36.200001,0.000000,36.200001,36.200001,0.00000,70.500000,0.547723,70.000000,71.000000,0.000000,100.000000,0.000000,100.0,100.0,0.0
18478,35.100002,75.000000,97.0,35.100002,0.000000,35.100002,35.100002,0.00000,74.666667,0.516398,74.000000,75.000000,1.000000,97.000000,0.000000,97.0,97.0,0.0

In [11]:
df.head()

,temperature,heart_rate,blood_oxygen,temperature_mean,temperature_std,temperature_min,temperature_max,temperature_change,heart_rate_mean,heart_rate_std,heart_rate_min,heart_rate_max,heart_rate_change,blood_oxygen_mean,blood_oxygen_std,blood_oxygen_min,blood_oxygen_max,blood_oxygen_change
0,36.299999,65.0,100.0,36.299999,0.0,36.299999,36.299999,0.0,65.000000,0.000000,65.0,65.0,0.0,100.000000,0.000000,100.0,100.0,0.0
1,36.900002,126.0,94.0,36.900002,0.0,36.900002,36.900002,0.0,106.666667,12.675436,91.0,126.0,35.0,97.833333,3.371449,93.0,100.0,-6.0
2,36.000000,65.0,100.0,36.000000,0.0,36.000000,36.000000,0.0,63.000000,2.097618,60.0,65.0,0.0,100.000000,0.000000,100.0,100.0,0.0
3,36.400002,60.0,97.0,36.400002,0.0,36.400002,36.400002,0.0,60.000000,0.000000,60.0,60.0,0.0,97.000000,0.000000,97.0,97.0,0.0
4,36.000000,66.0,97.0,36.000000,0.0,36.000000,36.000000,0.0,64.500000,1.048809,63.0,66.0,3.0,97.000000,0.000000,97.0,97.0,0.0